---
title: "Logistic Regression Predictions on all features"
author: "GMJ"
date: "2022-12-10"
output: html_document
---

```{r}
df = read.csv("df_with_months.csv")

df = subset(df, select = -c(time, X))
df
```


```{r}


  # create an empty dataframe to store the results

results_df <- data.frame(mcc=numeric(0), f1=numeric(0), accuracy=numeric(0), tp_rate=numeric(0), tn_rate=numeric(0), prc_auc=numeric(0), roc_auc=numeric(0))
colnames(results_df) = c("MCC", "F1 score", "accuracy", "TP rate", "TN rate", "PR AUC", "ROC AUC")

n = 100

for(i in 1:n) {
  
  df = df[sample(nrow(df)),]
  #https://towardsdatascience.com/survival-analysis-and-the-stratified-sample-2c2582aa9805
  # train the decision tree classifier on the training data
  #model <- rpart(DEATH_EVENT ~ ., data = train_data, importance=TRUE, proximity=TRUE)
  split <- createDataPartition(df$DEATH_EVENT, p = 0.8, list = FALSE)
  train_data <- df[split, ]
  test_data <- df[-split, ]
    # train the decision tree classifier on the training data
  
  model = glm(DEATH_EVENT ~ age + anaemia + creatinine_phosphokinase + diabetes + ejection_fraction + high_blood_pressure + platelets + serum_creatinine + serum_sodium + sex + smoking + as.factor(month), data = train_data, family = "binomial")
  
  #https://towardsdatascience.com/survival-analysis-and-the-stratified-sample-2c2582aa9805
  
  # evaluate the model on the test data
  predictions <- predict(model, test_data, type="response")
  
  predictions = ifelse(predictions >0.5, 1, 0)
  # evaluate the model on the test data
  
  
  confusion_matrix = confusionMatrix(as.factor(predictions), as.factor(test_data$DEATH_EVENT), mode = "everything")
  #print(confusion_matrix)
  accuracy <- confusion_matrix$overall[1]
  print(accuracy)
  
  rate = rates1(as.factor(predictions), as.factor(test_data$DEATH_EVENT))
  
  
  my_df = data.frame(rate)
  colnames(my_df) = c("MCC", "F1 score", "accuracy", "TP rate", "TN rate", "PR AUC", "ROC AUC")
  #colnames(results_df) = colnames(my_df)
  
  results_df = rbind(results_df, my_df)
}
print(results_df)
stat = stat.desc(results_df)
final_result = (stat)[c("median", "mean"),]
final_result
```

```{r}
write.csv(final_result, "log_reg_pred_all_features_results.csv")
```

```{r}
write.csv(results_df, "log_reg_pred_all_features_results_log.csv")
```

